<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Floppy.Unrailed2.Native.Windows.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/Floppy.Unrailed2/NativeCheats.cs" Link="NativeCheats.cs" />
  </ItemGroup>
</Project>
