<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Floppy.Unreal\Floppy.Unreal.csproj" />
    <ProjectReference Include="..\..\src\Floppy.Unrailed2\Floppy.Unrailed2.csproj" Aliases="Unrailed" />
  </ItemGroup>
</Project>
