<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <Version>1.7.2</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Floppy.Unreal\Floppy.Unreal.csproj" />
    <Compile Include="..\Shared\HostTakt.cs" Link="HostTakt.cs" />
    <InternalsVisibleTo Include="Floppy.Dungeons2.Tests" />
  </ItemGroup>
</Project>
